### PR TITLE
Setup.py improved

### LINKED ISSUE #4: Setup.py needs updates
Yes, I'm the owner of this project but this is completely honest.

We have gotten down to a solution, to view our plan click [here](https://github.com/NeilDevolopment/BeepBoopBot/issues/4#issuecomment-995648523)

**Is your feature request related to a problem? Please describe. (Optional)**
I'll be honest, the setup needs more updates and needs to be more user-friendly. You only get one choice, if you want logs or not and the text is not the best and can be better

**Describe the solution you'd like (Optional)**
Someone to change the text and make it better. It's not the best and it'd be great if the user knew how how get the information without visiting a webpage and you the configuration webpage is also fairly confusing for a starter

**Describe alternatives you've considered**
Maybe remove the you're gonna do this manually warning and add the stuff into the setup file & rename the wiki to manual configuration

**Additional context**

### PR DESCRIPTION
**Pull request by Neilisop**
This pull request has improved the setup.py file.

## What's new
Mainly everything from #4 has been added but here's all of it in short.
- [x] Setup 
- [x] Tutorial
- [x] Setup & Tutorial(Both)

## Summary
Every feature explained from now on.

**Tutorial:** This feature is for people who don't know much about Discord bots, or the devoloper mode to be honest. It will tell them how to get certain information on everything that is needed in the setup. Once it's ended it will ask the user if they want to go back to main area(the input that comes when you open up the script).

**Setup:** This is the old setup that was there before this pull request, nothing has been changed.

**Setup & Tutorial(Both):** This feature combines the setup with the tutorial, after every question(e.g. Please enter your bot token) there is information on how to get that thing. Such as how to get the token, admin role etc.

 Thanks!

Resolves #4

### CODE REVIEW

**Comment by Neilisop** [comment]
Please don't merge this right away, have a look into it and try it out if you want. It's not going to hurt anybody.

**Comment by TrueGamerTalha** [comment]
OMG its soo good. Btw how can I try it out?

**Comment by Neilisop** [comment]
Download the whole code or download the setup.py file itself, run it to test it out!

**Comment by TrueGamerTalha** [comment]
Can I run it on vsc?

**Comment by Neilisop** [comment]
Yeah you can, run the command `python3 setup.py` and it should work.

**Pull request merged**
